import type { Metadata } from 'next';
import { Geist_Mono, Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import { Header, CreatePlanModal, Footer } from '@/components';
import './globals.css';
import { Suspense } from 'react';
import { InviteModal } from '@/components/modals/InviteModal';

const notoSansKr = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const jalnan = localFont({
  src: '../public/fonts/Jalnan2.woff2',
  variable: '--jalnan-font',
  display: 'swap',
});

const jalnanGothic = localFont({
  src: '../public/fonts/JalnanGothic.woff2',
  variable: '--jalnan-gothic-font',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSansKr.variable} ${geistMono.variable} ${jalnan.variable} ${jalnanGothic.variable} h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col">
        <Header />

        {children}

        <Suspense fallback={null}>
          <InviteModal />
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
